### PR TITLE
chore(issue templates): bug-report, config, documentation, feature-request

### PR DESCRIPTION
**Pull request by ryparker**
Provided some basic issue templates to help submitters provide consistent and relevant info. This will also help organize issues by auto-labeling by issue type.

e.g. When a user submits a "Bug Report" it will automatically be labelled with `bug` (defined [here](https://github.com/ryparker/api.congress.gov/blob/bf3125d965469bd08ed22f9186a2457c087bdd10/.github/ISSUE_TEMPLATE/bug-report.yml?plain=1#L5))

GitHub issue template documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

### CODE REVIEW

**Review by CastelliOne — COMMENTED** [review]
Hi there,
Just to verify to better understand and ensure there is time saved when we have teams bridging  code that can inadvertently cause issues with overall access ... what exactly is the api name? Does it read rocket or blast off/ take off ... this is important in ensuring that the message gets across and we don't lose sight of the fact that we as a nation are attempting to cross reference and verify claims for misleading / misinformation. 

Thanks ! 
Johny Castelli

**Comment by CastelliOne** [comment]
> Hi there,
> Just to verify to better understand and ensure there is time saved when we have teams bridging  code that can inadvertently cause issues with overall access ... what exactly is the api name? Does it read rocket or blast off/ take off ... this is important in ensuring that the message gets across and we don't lose sight of the fact that we as a nation are attempting to cross reference and verify claims for misleading / misinformation. 
> 
> Thanks ! 
> Johny Castelli

🫡

**Comment by mnewatloc** [comment]
You can find our documentation, changelog, and readme files here: https://github.com/LibraryOfCongress/api.congress.gov

Let us know if you have further questions.

**Comment by ryparker** [comment]
Any particular reason why this was closed?

**Pull request closed without merging**
